[build-system]
requires = ["setuptools==67.7.1"]

[project]
name="c_doc_sphinx"
authors = [{ name="Raymond F. Wells", email="rfw2nd@gmail.com" }]
license = {text = "MIT"}
requires-python = ">= 3.9"

dependencies = [
  "pygments>=2.15,<3",
  "ujson>5,<6",
]
version = "0.0.1"


[tool.pyright]
